name: Dotnet Build and Publish
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build petssl_downloader
      run: dotnet build --configuration Release
    - name: Publish petssl_downloader (PublishSingleFile)
      run: dotnet publish -c Release -r win10-x64 /p:PublishSingleFile=true
    - name: Upload petssl-downloader.exe
      uses: actions/upload-artifact@v1
      with:
        name: PetSslDownloader
        path: C:\git\petssl-downloader\bin\Release\netcoreapp3.1\win10-x64\publish\petssl-downloader.exe
